# Generated by Django 4.1.3 on 2023-04-21 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_grocery_alter_product_add_about_p_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_Electronics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='Media')),
                ('title', models.CharField(max_length=50)),
                ('about_p', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='product_Fashion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='Media')),
                ('title', models.CharField(max_length=50)),
                ('about_p', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='product_Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='Media')),
                ('title', models.CharField(max_length=50)),
                ('about_p', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='product_Mobiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='Media')),
                ('title', models.CharField(max_length=50)),
                ('about_p', models.TextField()),
            ],
        ),
    ]
