# Generated by Django 4.1.3 on 2023-05-09 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_product_electronics_qnty_product_fashion_qnty_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_electronics',
            old_name='qnty',
            new_name='Quantity',
        ),
        migrations.RenameField(
            model_name='product_fashion',
            old_name='qnty',
            new_name='Quantity',
        ),
        migrations.RenameField(
            model_name='product_grocery',
            old_name='qnty',
            new_name='Quantity',
        ),
        migrations.RenameField(
            model_name='product_home',
            old_name='qnty',
            new_name='Quantity',
        ),
        migrations.RenameField(
            model_name='product_mobiles',
            old_name='qnty',
            new_name='Quantity',
        ),
    ]
