# Generated by Django 4.1.3 on 2023-05-09 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_rename_qnty_product_electronics_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_electronics',
            name='Price',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product_fashion',
            name='Price',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product_grocery',
            name='Price',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product_home',
            name='Price',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product_mobiles',
            name='Price',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product_electronics',
            name='Quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product_fashion',
            name='Quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product_grocery',
            name='Quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product_home',
            name='Quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product_mobiles',
            name='Quantity',
            field=models.IntegerField(),
        ),
    ]
