# Generated by Django 4.1.3 on 2023-05-19 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_product_add1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address_Add',
            fields=[
                ('user_login', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=100)),
                ('landmark', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=50)),
                ('pincode', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='product_Add1',
        ),
    ]
