# Generated by Django 4.1.3 on 2023-05-24 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_address_add_delete_product_add1'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_add_cart',
            name='category',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
